store/products/urls.py
from django.urls import path

from products.views import products, basket_add, basket_remove

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:category_id>', products, name='category'),
    path('page/<int:page_number>', products, name='paginator'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),

]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index, about, news

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('news/', news, name='news'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),





]

store/products/models.py
from django.db import models
from users.models import User


# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'Product: {self.name} | Category: {self.category.name}'


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Basket for {self.user.username} | Product: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

store/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', null=True, blank=True)

store/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Enter your name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Enter your surname'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Choose a username'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Enter your email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Choose a password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Confirm your password'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-2'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-2'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-2', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-2', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

store/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from products.models import Product, ProductCategory, Basket
from django.core.paginator import Paginator


def index(request):
    context = {
        'tittle': 'Mangastore',
        'username': 'Sanzhar',
    }
    return render(request, 'products/index.html', context)


def about(request):
    return render(request, 'products/about.html')


def news(request):
    return render(request, 'products/news.html')


def products(request, category_id=None, page_number=1):
    products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()

    per_page = 6
    paginator = Paginator(products, per_page)
    products_paginator = paginator.page(page_number)

    context = {
        'title': 'Mangastore - products',
        'categories': ProductCategory.objects.all(),
        'products': products_paginator,

    }

    return render(request, 'products/products.html', context)


def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

store/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse

from users.models import User
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from products.models import Basket


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you! Your registration was successful')
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)

    baskets = Basket.objects.filter(user=request.user)
    total_sum = 0
    total_quantity = 0
    for basket in baskets:
        total_sum = total_sum + basket.sum()
        total_quantity = total_quantity + basket.quantity

    context = {
        'title': 'Mangastore - profile',
        'form': form,
        'baskets': Basket.objects.filter(user=request.user),
        'total_sum': total_sum,
        'total_quantity': total_quantity,
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

store/products/templates/products/about.html
{% extends 'products/base.html' %}

{% block css %}<link rel="stylesheet" type="text/css" href="/static/about.css"> {% endblock %}

{% block content %}

  <div class="container-fluid" id="c1" >

<div class="container" >
    <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <h1 style=" text-align: left; margin-top: 5rem; font-size: 2.50rem;">Get Lost in the World of Manga with Our Online Store - Manga Store</h1>
    <p class="text" style="font-size: 22px; font-weight: 100; width: 550px;">Welcome to our online store, where we provide an extensive collection of manga from all genres to satisfy every fan's cravings. Our passion for manga led us to create this platform, where we can share our love for this unique art form with others.</p>

  </div>
  <br><br><br>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"><img src="/static/img/bg2.png" alt="Example Image" style="margin-top: 90px; width: 410px; border-radius: 30px; margin-left:100px;"></div>
   </div>

</div>

</div>


<br><br><br><br><br>
<h1 style="text-align: center; font-size: 48px;">Why did we create Manga Store?</h1>
<p style="text-align: center; font-size: 20px; color: #757575;">We are excited to offer our platform to manga lovers in Kazakhstan</p>


<div class="container" style="width: 1000px;">
  <br><br> <br><br>
  <div class="row">

    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"><img src="/static/img/anya.png" width="400px"></div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"><h2>Wide range of manga titles</h2><br><br><p style="color:#757575; font-size: 20px;">Our online store provides a wide range of manga
       titles from all genres, including shonen, shojo, seinen, and josei, catering to the diverse tastes of manga readers in Kazakhstan.</p></div>
  </div>
  <br><br>
  <div class="row">
    <br><br>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"><h2>Every Manga Is<br>Authentic And Of The<br> Highest Quality</h2><br><br><p style="color:#757575; font-size: 20px;">We understand the passion and enthusiasm that manga lovers in Kazakhstan have for this unique art form, and we are committed to providing genuine and high-quality manga that meets their expectations.</p></div>
       <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"><img src="/static/img/luffy.png" width="400px"></div>
  </div>
  <br><br>
  <div class="row">

    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"><img src="/static/img/girl.png" width="400px"></div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6"><h2>Wide range of manga titles</h2><br><br><p style="color:#757575; font-size: 20px;">Our online store provides a wide range of manga
       titles from all genres, including shonen, shojo, seinen, and josei, catering to the diverse tastes of manga readers in Kazakhstan.</p></div>
  </div>
</div>

</div>


<br><br><br><br><br><br>{% endblock %}



store/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ tittle }}</title>

   {% block css %} {% endblock %}



    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>


  <header class="navbar">
    <a href="#" class="logo"><img src="/static/img/Rectangle.svg" style="width: 105px;"></a>

    <nav class="nav-links">


      <a href="index.html"><p style="font-weight: 600;">Main page</p></a>
      <a href="{% url 'about' %}"><p>About us</p></a>
      <a href="{% url 'news' %}"><p>News</p></a>
      <a href="{% url 'products:index' %}"><p>Products</p></a>
        {% if user.is_authenticated %}
        <nav class="right-links">
                   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
           data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user-circle"></i>
        </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
            <a class="dropdown-item" href="#">Orders</a>
              {% if user.is_superuser or user.is_staff%}
                  <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
              {% endif %}
            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
          </div>
        </div>
    </nav>

        {% else %}
            <a href="{% url 'users:login' %}"><p>Login</p></a>
         {% endif %}
    </nav>
  </header>

  {% block content %} {% endblock %}

  {% block footer %}

   <footer>
    <div class="icons">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-youtube"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-whatsapp"></i></a>
    </div>
  </footer>
  {% endblock %}
  <script src="/static/script.js"></script>
  <script src="https://kit.fontawesome.com/143aa7dc55.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>
</html>

store/products/templates/products/basket.html
{% if baskets %}
        <div class="col-lg-5" style="margin-left: 450px">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Basket <span class="badge badge-secondary badge-pill">3</span>
            </h4>
             {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }}</div>
                            <div class="col-lg-4">
                                <a href="{% url 'products:basket_remove' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>


            {% endfor %}
            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Total:</p>
                    <h4 class="float-right">{{ total_sum }} Tg</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html" style="background: linear-gradient(to right, #762424 0%, #000000 100%);
                  color: white;
                  border: none;
                  border-radius: 15px;
                  cursor: pointer;">
                Make an order
            </a>
    </div>

{% else %}
     <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3" style="margin-left: 450px">
                Basket is empty
            </h4>
{% endif %}

store/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
     <link rel="stylesheet" type="text/css" href="/static/styles.css">
{% endblock %}

{% block content %}
     <br><br>
  <div class="container-fluid">
    <img src="/static/img/bg.png" alt="banner" style="width: 800px;max-width: 100%; margin: auto;">
  </div>

  <br><br><br>
  <div class="container-fluid" id="news">
    <h1 class="responsive-header" style="margin-left: 180px;">News</h1>
    <div class="card-container">
      <div class="card" style="background-image: url('/static/img/cart1.png');">
          <div class="text-container">
            <br><br><br><br><br><br>
              <div class="text1">Name</div>
              <div class="text2">Description</div>
          </div>
          <div class="more"><a href="#" style="text-decoration: none; color: white;" >More</a></div>
      </div>
      <div class="card" style="background-image: url('/static/img/cart2.png');">
          <div class="text-container">
            <br><br><br><br><br><br>
              <div class="text1">Name</div>
              <div class="text2">Description</div>
          </div>
          <div class="more"><a href="#" style="text-decoration: none; color: white;" >More</a></div>
      </div>
      <div class="card" style="background-image: url('/static/img/cart3.png');">
          <div class="text-container">
            <br><br><br><br><br><br>
              <div class="text1">Name</div>
              <div class="text2">Description</div>
          </div>
          <div class="more"><a href="#" style="text-decoration: none; color: white;" >More</a></div>
      </div>
  </div>
  </div>


  <br><br><br><br>
  <div class="container-fluid" id="news">
    <h1 class="responsive-header" style="margin-left: 180px;">Products</h1>
    <div class="card-container">
      <div class="card" style="background-image: url('/static/img/pr1.png');">
          <div class="text-container">
            <br><br><br><br><br><br>
              <div class="text1">One piece</div>
              <div class="text2">(1-6 toms are available)</div>
          </div>
          <div class="more"><a href="#" style="text-decoration: none; color: white;" ><button type="button" id="btn1" class="btn">Explore</button></a></div>
      </div>
      <div class="card" style="background-image: url('/static/img/pr2.png');">
          <div class="text-container">
            <br><br><br><br><br><br>
              <div class="text1">Demon slayer</div>
              <div class="text2">All toms are available</div>
          </div>
          <div class="more"><a href="#" style="text-decoration: none; color: white;" ><button type="button" id="btn1" class="btn">Explore</button></a></div>
      </div>
      <div class="card" style="background-image: url('/static/img/pr3.png');">
          <div class="text-container">
            <br><br><br><br><br><br>
              <div class="text1">Chainsaw man</div>
              <div class="text2">All toms are available!</div>
          </div>
          <div class="more"><a href="#" style="text-decoration: none; color: white;" ><button type="button" id="btn1" class="btn">Explore</button></a></div>
      </div>
  </div>
  </div>
   <br><br><br><br><br><br>
{% endblock %}



store/products/templates/products/products.html
{% extends 'products/base.html' %}

{% block css %}<link rel="stylesheet" type="text/css" href="/static/products.css"> {% endblock %}


{% block content %} <br><br><br><br><br>

  <div class="container" id="prod">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in categories %}

                <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category.name }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <div class="slides">
            <div id="carouselExampleIndicators" class="carousel slide">
              <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
              </div>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="/static/img/anya2.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                  <img src="/static/img/car2.svg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                  <img src="/static/img/car1.svg" class="d-block w-100" alt="...">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
            </div>
            <br><br>
            <div class="row">
                {% for product in products %}
                    <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }} Tg</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:basket_add' product.id%}">
                                Add to cart
                            </a>

                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if products.has_previous %} {% url 'products:paginator' products.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    {% for page in products.paginator.page_range %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'products:paginator' page %}">
                                {{ page }}
                            </a>
                        </li>
                    {% endfor %}


                    <li class="page-item {% if not products.has_next %} disabled {% endif  %}">
                        <a class="page-link" href="{% if products.has_next %} {% url 'products:paginator' products.next_page_number %} {% else %} # {% endif %}">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
<!-- /.container -->
<br><br><br><br><br><br> {% endblock %}





store/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ tittle }}</title>

   {% block css %} {% endblock %}



    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>

  <header class="navbar">
    <a href="#" class="logo"><img src="/static/img/Rectangle.svg" style="width: 105px;"></a>

    <nav class="nav-links">


      <a href="index.html"><p style="font-weight: 600;">Main page</p></a>
      <a href="{% url 'about' %}"><p>About us</p></a>
      <a href="{% url 'news' %}"><p>News</p></a>
      <a href="{% url 'products:index' %}"><p>Products</p></a>
        {% if user.is_authenticated %}
        <nav class="right-links">
                   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
           data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user-circle"></i>
        </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
            <a class="dropdown-item" href="#">Orders</a>
            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
          </div>
        </div>
    </nav>

        {% else %}
            <a href="{% url 'users:login' %}"><p>Login</p></a>
         {% endif %}
    </nav>


  </header>


  {% block content %} {% endblock %}

  {% block footer %}

   <footer>
    <div class="icons">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-youtube"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-whatsapp"></i></a>
    </div>
  </footer>
  {% endblock %}
  <script src="/static/script.js"></script>
  <script src="https://kit.fontawesome.com/143aa7dc55.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>
</html>

store/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
     <link rel="stylesheet" type="text/css" href="/static/users.css">
{% endblock %}

{% block content %}



  <div class="login-container" style="width: 500px; justify-content: center">
  {% if messages or form.non_field_errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 1px;">
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% else %}
            {{ form.non_field_errors }}
        {% endif %}
        </div>
    {% endif %}
  <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}

    <h2 style="color: #762424;">Log In</h2>
      <div class="form-group">
      {{ form.username }}
          </div>
       <div class="form-group">

           {{ form.password }}
           </div>
      <a href="forgot_password.php">Forgot password?</a>
    <br><br>

      <button type="submit"><p style="font-size: 14px;">Log In</p></button>
    <br><br>
    <p><a href="{% url 'users:registration' %}">Don't have an account? Sign up</a></p>
      </form>
  </div>
    <br><br><br><br><br><br><br>
{% endblock %}

store/users/templates/users/register.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
     <link rel="stylesheet" type="text/css" href="/static/users.css">
{% endblock %}

{% block content %}

<br>
  <style>


    .container {
      max-width: 700px;
      margin: 0 auto;
      padding: 20px;
      background-color: #ffffff;
      border-radius: 5px;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
      color:  #762424;
         box-shadow: 0 0 10px #d5e3f3;
    }

    h2 {
      text-align: center;
    }

    .form-group {
      margin-bottom: 15px;
    }

    .form-group label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;

    }

    .form-group input {
      width: 100%;
      height: 10px;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    .form-group input[type="submit"] {
      background-color:  #762424;
      color: #fff;
      cursor: pointer;
    }



  </style>

  <div class="container">
      {% if form.errors %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 1px;">
         {{ form.errors }}
        </div>
    {% endif %}
    <h2>Registration Form</h2>
    <form action="{% url 'users:registration' %}" method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">Name:</label>
          {{ form.first_name }}
      </div>
      <div class="form-group">
        <label  for="{{ form.last_name.id_for_label }}">Surname:</label>
        {{ form.last_name }}
      </div>
      <div class="form-group">
        <label   for="{{ form.username.id_for_label }}">Username:</label>
       {{ form.username }}
      </div>
      <div class="form-group">
        <label  for="{{ form.email.id_for_label }}">Email:</label>
        {{ form.email }}
      </div>
      <div  class="form-group">
        <label for="{{ form.password1.id_for_label }}">Password:</label>
        {{ form.password1 }}
      </div>
      <div  class="form-group">
        <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
          {{ form.password2 }}
      </div>
      <div   class="form-group">
          <input class="form-control py-4" type="submit" value="Register" style="height: 70px">
      </div>
    </form>
  <p ><a href="{% url 'users:login'%}" style="text-decoration: none; color: black; font-size: 19px; margin-left: 5px ">Already have an account? Log in</a></p>
  </div>

<br><br><br>


{% endblock %}